[package]
name = "spatial-import-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdal = "0.16.0"
wkb-raster = "0.2.1"
actix-web = "4.5.1"